<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ChatSnippets.Core\ChatSnippets.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>ChatSnippets</AssemblyName>
    <RootNamespace>ChatSnippets.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\chat-snippets.ico</ApplicationIcon>
    <Authors>Егоров Сергей aka Evpatiy</Authors>
    <Company>Егоров Сергей aka Evpatiy</Company>
    <Product>ClaudeCode Chat Snippets</Product>
    <Version>1.0.2</Version>
  </PropertyGroup>

</Project>

